version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actual-app-api:
        patterns:
          - "@actual-app/api"
      all-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@actual-app/api"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
